export interface EpgSource {
  code: string;
  name: string;
  url: string;
}

export const EPG_SOURCES: EpgSource[] = [
  { code: "AL", name: "Albania", url: "https://iptv-epg.org/files/epg-al.xml.gz" },
  { code: "AR", name: "Argentina", url: "https://iptv-epg.org/files/epg-ar.xml.gz" },
  { code: "AM", name: "Armenia", url: "https://iptv-epg.org/files/epg-am.xml.gz" },
  { code: "AU", name: "Australia", url: "https://iptv-epg.org/files/epg-au.xml.gz" },
  { code: "AT", name: "Austria", url: "https://iptv-epg.org/files/epg-at.xml.gz" },
  { code: "BS", name: "Bahamas", url: "https://iptv-epg.org/files/epg-bs.xml.gz" },
  { code: "BY", name: "Belarus", url: "https://iptv-epg.org/files/epg-by.xml.gz" },
  { code: "BE", name: "Belgium", url: "https://iptv-epg.org/files/epg-be.xml.gz" },
  { code: "BO", name: "Bolivia", url: "https://iptv-epg.org/files/epg-bo.xml.gz" },
  { code: "BA", name: "Bosnia & Herzegovina", url: "https://iptv-epg.org/files/epg-ba.xml.gz" },
  { code: "BR", name: "Brazil", url: "https://iptv-epg.org/files/epg-br.xml.gz" },
  { code: "BG", name: "Bulgaria", url: "https://iptv-epg.org/files/epg-bg.xml.gz" },
  { code: "CA", name: "Canada", url: "https://iptv-epg.org/files/epg-ca.xml.gz" },
  { code: "CL", name: "Chile", url: "https://iptv-epg.org/files/epg-cl.xml.gz" },
  { code: "CO", name: "Colombia", url: "https://iptv-epg.org/files/epg-co.xml.gz" },
  { code: "CR", name: "Costa Rica", url: "https://iptv-epg.org/files/epg-cr.xml.gz" },
  { code: "HR", name: "Croatia", url: "https://iptv-epg.org/files/epg-hr.xml.gz" },
  { code: "CW", name: "Curaçao", url: "https://iptv-epg.org/files/epg-cw.xml.gz" },
  { code: "CZ", name: "Czech Republic", url: "https://iptv-epg.org/files/epg-cz.xml.gz" },
  { code: "DK", name: "Denmark", url: "https://iptv-epg.org/files/epg-dk.xml.gz" },
  { code: "DO", name: "Dominican Republic", url: "https://iptv-epg.org/files/epg-do.xml.gz" },
  { code: "EG", name: "Egypt", url: "https://iptv-epg.org/files/epg-eg.xml.gz" },
  { code: "SV", name: "El Salvador", url: "https://iptv-epg.org/files/epg-sv.xml.gz" },
  { code: "FI", name: "Finland", url: "https://iptv-epg.org/files/epg-fi.xml.gz" },
  { code: "FR", name: "France", url: "https://iptv-epg.org/files/epg-fr.xml.gz" },
  { code: "GE", name: "Georgia", url: "https://iptv-epg.org/files/epg-ge.xml.gz" },
  { code: "DE", name: "Germany", url: "https://iptv-epg.org/files/epg-de.xml.gz" },
  { code: "GH", name: "Ghana", url: "https://iptv-epg.org/files/epg-gh.xml.gz" },
  { code: "GR", name: "Greece", url: "https://iptv-epg.org/files/epg-gr.xml.gz" },
  { code: "GT", name: "Guatemala", url: "https://iptv-epg.org/files/epg-gt.xml.gz" },
  { code: "HN", name: "Honduras", url: "https://iptv-epg.org/files/epg-hn.xml.gz" },
  { code: "HK", name: "Hong Kong", url: "https://iptv-epg.org/files/epg-hk.xml.gz" },
  { code: "HU", name: "Hungary", url: "https://iptv-epg.org/files/epg-hu.xml.gz" },
  { code: "IS", name: "Iceland", url: "https://iptv-epg.org/files/epg-is.xml.gz" },
  { code: "IN", name: "India", url: "https://iptv-epg.org/files/epg-in.xml.gz" },
  { code: "ID", name: "Indonesia", url: "https://iptv-epg.org/files/epg-id.xml.gz" },
  { code: "IL", name: "Israel", url: "https://iptv-epg.org/files/epg-il.xml.gz" },
  { code: "IT", name: "Italy", url: "https://iptv-epg.org/files/epg-it.xml.gz" },
  { code: "JM", name: "Jamaica", url: "https://iptv-epg.org/files/epg-jm.xml.gz" },
  { code: "LB", name: "Lebanon", url: "https://iptv-epg.org/files/epg-lb.xml.gz" },
  { code: "LT", name: "Lithuania", url: "https://iptv-epg.org/files/epg-lt.xml.gz" },
  { code: "LU", name: "Luxembourg", url: "https://iptv-epg.org/files/epg-lu.xml.gz" },
  { code: "MK", name: "North Macedonia", url: "https://iptv-epg.org/files/epg-mk.xml.gz" },
  { code: "MY", name: "Malaysia", url: "https://iptv-epg.org/files/epg-my.xml.gz" },
  { code: "MT", name: "Malta", url: "https://iptv-epg.org/files/epg-mt.xml.gz" },
  { code: "MX", name: "Mexico", url: "https://iptv-epg.org/files/epg-mx.xml.gz" },
  { code: "ME", name: "Montenegro", url: "https://iptv-epg.org/files/epg-me.xml.gz" },
  { code: "NL", name: "Netherlands", url: "https://iptv-epg.org/files/epg-nl.xml.gz" },
  { code: "NZ", name: "New Zealand", url: "https://iptv-epg.org/files/epg-nz.xml.gz" },
  { code: "NI", name: "Nicaragua", url: "https://iptv-epg.org/files/epg-ni.xml.gz" },
  { code: "NG", name: "Nigeria", url: "https://iptv-epg.org/files/epg-ng.xml.gz" },
  { code: "NO", name: "Norway", url: "https://iptv-epg.org/files/epg-no.xml.gz" },
  { code: "PY", name: "Paraguay", url: "https://iptv-epg.org/files/epg-py.xml.gz" },
  { code: "PE", name: "Peru", url: "https://iptv-epg.org/files/epg-pe.xml.gz" },
  { code: "PH", name: "Philippines", url: "https://iptv-epg.org/files/epg-ph.xml.gz" },
  { code: "PL", name: "Poland", url: "https://iptv-epg.org/files/epg-pl.xml.gz" },
  { code: "PT", name: "Portugal", url: "https://iptv-epg.org/files/epg-pt.xml.gz" },
  { code: "RO", name: "Romania", url: "https://iptv-epg.org/files/epg-ro.xml.gz" },
  { code: "RU", name: "Russia", url: "https://iptv-epg.org/files/epg-ru.xml.gz" },
  { code: "RS", name: "Serbia", url: "https://iptv-epg.org/files/epg-rs.xml.gz" },
  { code: "SG", name: "Singapore", url: "https://iptv-epg.org/files/epg-sg.xml.gz" },
  { code: "SI", name: "Slovenia", url: "https://iptv-epg.org/files/epg-si.xml.gz" },
  { code: "ZA", name: "South Africa", url: "https://iptv-epg.org/files/epg-za.xml.gz" },
  { code: "KR", name: "South Korea", url: "https://iptv-epg.org/files/epg-kr.xml.gz" },
  { code: "ES", name: "Spain", url: "https://iptv-epg.org/files/epg-es.xml.gz" },
  { code: "SE", name: "Sweden", url: "https://iptv-epg.org/files/epg-se.xml.gz" },
  { code: "CH", name: "Switzerland", url: "https://iptv-epg.org/files/epg-ch.xml.gz" },
  { code: "TW", name: "Taiwan", url: "https://iptv-epg.org/files/epg-tw.xml.gz" },
  { code: "TH", name: "Thailand", url: "https://iptv-epg.org/files/epg-th.xml.gz" },
  { code: "TT", name: "Trinidad & Tobago", url: "https://iptv-epg.org/files/epg-tt.xml.gz" },
  { code: "TR", name: "Turkey", url: "https://iptv-epg.org/files/epg-tr.xml.gz" },
  { code: "UG", name: "Uganda", url: "https://iptv-epg.org/files/epg-ug.xml.gz" },
  { code: "UA", name: "Ukraine", url: "https://iptv-epg.org/files/epg-ua.xml.gz" },
  { code: "AE", name: "United Arab Emirates", url: "https://iptv-epg.org/files/epg-ae.xml.gz" },
  { code: "GB", name: "United Kingdom", url: "https://iptv-epg.org/files/epg-gb.xml.gz" },
  { code: "US", name: "United States", url: "https://iptv-epg.org/files/epg-us.xml.gz" },
  { code: "UY", name: "Uruguay", url: "https://iptv-epg.org/files/epg-uy.xml.gz" },
  { code: "VE", name: "Venezuela", url: "https://iptv-epg.org/files/epg-ve.xml.gz" },
  { code: "ZW", name: "Zimbabwe", url: "https://iptv-epg.org/files/epg-zw.xml.gz" }
];
