import type { ComponentType } from "react"
import {
  AudioLines,
  Baby,
  Bike,
  BookOpen,
  Bookmark,
  BriefcaseBusiness,
  Camera,
  Car,
  ChefHat,
  Church,
  Circle,
  Clapperboard,
  Compass,
  Crown,
  Disc,
  Drama,
  Dumbbell,
  Film,
  Flag,
  Flame,
  Folder,
  Gamepad2,
  Gavel,
  Globe,
  Goal,
  GraduationCap,
  Guitar,
  Headphones,
  Heart,
  House,
  IceCreamCone,
  Landmark,
  Leaf,
  Medal,
  Mic,
  MountainSnow,
  Music,
  Newspaper,
  PawPrint,
  Pin,
  Plane,
  Popcorn,
  Puzzle,
  Radio,
  RadioTower,
  Rocket,
  Rss,
  School,
  Shirt,
  ShoppingCart,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  Swords,
  Tag,
  Target,
  Theater,
  Ticket,
  TrendingUp,
  Trophy,
  TvMinimal,
  Video,
  Volleyball,
  WavesHorizontal,
  Zap,
  type LucideProps,
} from "lucide-react-native"

/**
 * The icon a favourite group was saved with.
 *
 * Keyed by the same ids the web's picker writes, so a group given the cricket
 * icon there arrives here as that icon rather than a stand-in. The map lives
 * per platform because the id is what is stored — the component it resolves to
 * cannot cross into shared code.
 *
 * Three ids resolve to a different component than on the web, because
 * lucide-react-native does not ship the name lucide-react does: Waves,
 * Podcast and Globe2. The nearest equivalent is used rather than leaving them
 * blank, which is what an unknown name would otherwise produce.
 */
const GROUP_ICONS: Record<string, ComponentType<LucideProps>> = {
  goal: Goal,
  volleyball: Volleyball,
  cycling: Bike,
  swimming: WavesHorizontal,
  climbing: MountainSnow,
  darts: Target,
  combat: Swords,
  dumbbell: Dumbbell,
  trophy: Trophy,
  medal: Medal,
  racing: Flag,
  film: Film,
  clapperboard: Clapperboard,
  popcorn: Popcorn,
  tv: TvMinimal,
  theatre: Theater,
  drama: Drama,
  events: Ticket,
  video: Video,
  gamepad: Gamepad2,
  music: Music,
  radio: Radio,
  podcast: Rss,
  headphones: Headphones,
  albums: Disc,
  livemusic: Guitar,
  talk: Mic,
  audio: AudioLines,
  news: Newspaper,
  globe: Globe,
  book: BookOpen,
  education: GraduationCap,
  politics: Landmark,
  law: Gavel,
  business: BriefcaseBusiness,
  markets: TrendingUp,
  live: RadioTower,
  school: School,
  baby: Baby,
  puzzle: Puzzle,
  treats: IceCreamCone,
  animals: PawPrint,
  space: Rocket,
  fun: Smile,
  house: House,
  food: ChefHat,
  travel: Plane,
  shopping: ShoppingCart,
  fashion: Shirt,
  health: Stethoscope,
  faith: Church,
  nature: Leaf,
  cars: Car,
  photography: Camera,
  star: Star,
  heart: Heart,
  sparkles: Sparkles,
  bookmark: Bookmark,
  trending: Flame,
  quick: Zap,
  premium: Crown,
  collection: Folder,
  tag: Tag,
  pinned: Pin,
  discover: Compass,
  plain: Circle,
}

/** Star is the web's fallback for an id it does not know, so it is ours. */
export function GroupIcon({
  icon,
  size = 16,
  color,
}: {
  icon: string | undefined
  size?: number
  color: string
}) {
  const Icon = (icon && GROUP_ICONS[icon]) || Star
  return <Icon size={size} color={color} />
}
